version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: cms_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: CMSProject/Dockerfile
    container_name: cms_api
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=cms_db;Username=cms_user;Password=123456
      - Jwt__Key=Lqg!zF9kdXf$3PVt@cRbmT5U9&w#X4MAQZN6E^uhJyK!vdR28bYjNqGHs*7Xp3Lm
      - Jwt__Issuer=CMSAuth
      - Jwt__Audience=CMSFrontend
      - Jwt__ExpirationInMinutes=60
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
